const {
  REACT_APP_SERVER_HOST: SERVER_HOST,
  REACT_APP_SERVER_PORT: SERVER_PORT,
  REACT_APP_PRODUCTION_SERVER_HOST: PROD_HOST,
  REACT_APP_NAVER_PAPAGO_URL: NAVER_PAPAGO_URL,
  REACT_APP_KAKAO_API_URL: KAKAO_API_URL,
} = process.env;

export { SERVER_HOST, SERVER_PORT, PROD_HOST, NAVER_PAPAGO_URL, KAKAO_API_URL };
